### ISSUE TITLE
Will not make

### ISSUE THREAD

**Issue by Jazzoo** [ardi69/42tiny-js#26]
Sorry if this is not relevant but ...

uname -a 
Linux MediaII 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

running make fails 

make
TinyJS.cpp
In file included from TinyJS.h:53:0,
                 from TinyJS.cpp:50:
config.h:221:17: warning: missing terminating " character [enabled by default]
 #pragma message("\n**********************************************************************_\n\
                 ^
config.h:224:74: warning: missing terminating " character [enabled by default]
 ***_******************************************************************_\n")
                                                                          ^
In file included from TinyJS.cpp:50:0:
TinyJS.h: In function ‘CScriptVarPtr newScriptVar(CTinyJS_, int64_t)’:
TinyJS.h:1177:56: error: redefinition of ‘CScriptVarPtr newScriptVar(CTinyJS_, int64_t)’
 #define define_newScriptVar_Fnc(t1, ...) CScriptVarPtr newScriptVar(**VA_ARGS**)
                                                        ^
TinyJS.h:1476:8: note: in expansion of macro ‘define_newScriptVar_Fnc’
 inline define_newScriptVar_Fnc(Number, CTinyJS *Context, int64_t Obj) { return newScriptVarNumber(Context, CNumber(Obj)); }
        ^
TinyJS.h:1177:56: error: ‘CScriptVarPtr newScriptVar(CTinyJS_, long int)’ previously defined here
 #define define_newScriptVar_Fnc(t1, ...) CScriptVarPtr newScriptVar(**VA_ARGS**)
                                                        ^
TinyJS.h:1475:8: note: in expansion of macro ‘define_newScriptVar_Fnc’
 inline define_newScriptVar_Fnc(Number, CTinyJS _Context, long Obj) { return newScriptVarNumber(Context, CNumber((int32_t)Obj)); }
        ^
TinyJS.cpp: In member function ‘CScriptVarPtr CScriptVarRegExp::exec(const string&, bool)’:
TinyJS.cpp:4491:36: error: call of overloaded ‘int2string(std::match_results<__gnu_cxx::__normal_iterator<const char_, std::basic_string<char> > >::size_type&)’ is ambiguous
     retVar->addChild(int2string(idx), newScriptVar(match[idx].str()));
                                    ^
TinyJS.cpp:4491:36: note: candidates are:
TinyJS.cpp:178:8: note: std::string int2string(int32_t)
 string int2string(int32_t intData) {
        ^
TinyJS.cpp:183:8: note: std::string int2string(uint32_t)
 string int2string(uint32_t intData) {
        ^
TinyJS.cpp: In member function ‘void CTinyJS::native_Generator_prototype_next(const CFunctionsScopePtr&, void_)’:
TinyJS.cpp:7104:44: error: cast from ‘void_’ to ‘int’ loses precision [-fpermissive]
   c->throwError(TypeError, string(fnc[(int)data])+" method called on incompatible Object");
                                            ^
TinyJS.cpp:7106:10: error: cast from ‘void_’ to ‘int’ loses precision [-fpermissive]
  if((int)data >=2)
          ^
TinyJS.cpp:7107:44: error: cast from ‘void_’ to ‘int’ loses precision [-fpermissive]
   Generator->native_throw(c, (void_)(((int)data)-2));
                                            ^
TinyJS.cpp:7107:51: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   Generator->native_throw(c, (void_)(((int)data)-2));
                                                   ^
make: **\* [TinyJS.o] Error 1

**Comment by ardi69** [comment]
fixed
